// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: server_example.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HiddenData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HiddenData) Reset() {
	*x = HiddenData{}
	mi := &file_server_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HiddenData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiddenData) ProtoMessage() {}

func (x *HiddenData) ProtoReflect() protoreflect.Message {
	mi := &file_server_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiddenData.ProtoReflect.Descriptor instead.
func (*HiddenData) Descriptor() ([]byte, []int) {
	return file_server_example_proto_rawDescGZIP(), []int{0}
}

func (x *HiddenData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublicData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicData) Reset() {
	*x = PublicData{}
	mi := &file_server_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicData) ProtoMessage() {}

func (x *PublicData) ProtoReflect() protoreflect.Message {
	mi := &file_server_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicData.ProtoReflect.Descriptor instead.
func (*PublicData) Descriptor() ([]byte, []int) {
	return file_server_example_proto_rawDescGZIP(), []int{1}
}

func (x *PublicData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NoArguments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoArguments) Reset() {
	*x = NoArguments{}
	mi := &file_server_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoArguments) ProtoMessage() {}

func (x *NoArguments) ProtoReflect() protoreflect.Message {
	mi := &file_server_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoArguments.ProtoReflect.Descriptor instead.
func (*NoArguments) Descriptor() ([]byte, []int) {
	return file_server_example_proto_rawDescGZIP(), []int{2}
}

var File_server_example_proto protoreflect.FileDescriptor

const file_server_example_proto_rawDesc = "" +
	"\n" +
	"\x14server_example.proto\x12\x0eserver_example\"&\n" +
	"\n" +
	"HiddenData\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"&\n" +
	"\n" +
	"PublicData\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\r\n" +
	"\vNoArguments2\xfb\x01\n" +
	"\rServerExample\x12J\n" +
	"\rGetHiddenData\x12\x1b.server_example.NoArguments\x1a\x1a.server_example.HiddenData\"\x00\x12R\n" +
	"\x13GetHiddenStreamData\x12\x1b.server_example.NoArguments\x1a\x1a.server_example.HiddenData\"\x000\x01\x12J\n" +
	"\rGetPublicData\x12\x1b.server_example.NoArguments\x1a\x1a.server_example.PublicData\"\x00B\tZ\a./;mainb\x06proto3"

var (
	file_server_example_proto_rawDescOnce sync.Once
	file_server_example_proto_rawDescData []byte
)

func file_server_example_proto_rawDescGZIP() []byte {
	file_server_example_proto_rawDescOnce.Do(func() {
		file_server_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_example_proto_rawDesc), len(file_server_example_proto_rawDesc)))
	})
	return file_server_example_proto_rawDescData
}

var file_server_example_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_server_example_proto_goTypes = []any{
	(*HiddenData)(nil),  // 0: server_example.HiddenData
	(*PublicData)(nil),  // 1: server_example.PublicData
	(*NoArguments)(nil), // 2: server_example.NoArguments
}
var file_server_example_proto_depIdxs = []int32{
	2, // 0: server_example.ServerExample.GetHiddenData:input_type -> server_example.NoArguments
	2, // 1: server_example.ServerExample.GetHiddenStreamData:input_type -> server_example.NoArguments
	2, // 2: server_example.ServerExample.GetPublicData:input_type -> server_example.NoArguments
	0, // 3: server_example.ServerExample.GetHiddenData:output_type -> server_example.HiddenData
	0, // 4: server_example.ServerExample.GetHiddenStreamData:output_type -> server_example.HiddenData
	1, // 5: server_example.ServerExample.GetPublicData:output_type -> server_example.PublicData
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_example_proto_init() }
func file_server_example_proto_init() {
	if File_server_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_example_proto_rawDesc), len(file_server_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_example_proto_goTypes,
		DependencyIndexes: file_server_example_proto_depIdxs,
		MessageInfos:      file_server_example_proto_msgTypes,
	}.Build()
	File_server_example_proto = out.File
	file_server_example_proto_goTypes = nil
	file_server_example_proto_depIdxs = nil
}
