// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: server_example.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HiddenData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HiddenData) Reset() {
	*x = HiddenData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HiddenData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HiddenData) ProtoMessage() {}

func (x *HiddenData) ProtoReflect() protoreflect.Message {
	mi := &file_server_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HiddenData.ProtoReflect.Descriptor instead.
func (*HiddenData) Descriptor() ([]byte, []int) {
	return file_server_example_proto_rawDescGZIP(), []int{0}
}

func (x *HiddenData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublicData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *PublicData) Reset() {
	*x = PublicData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublicData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicData) ProtoMessage() {}

func (x *PublicData) ProtoReflect() protoreflect.Message {
	mi := &file_server_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicData.ProtoReflect.Descriptor instead.
func (*PublicData) Descriptor() ([]byte, []int) {
	return file_server_example_proto_rawDescGZIP(), []int{1}
}

func (x *PublicData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NoArguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoArguments) Reset() {
	*x = NoArguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_example_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoArguments) ProtoMessage() {}

func (x *NoArguments) ProtoReflect() protoreflect.Message {
	mi := &file_server_example_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoArguments.ProtoReflect.Descriptor instead.
func (*NoArguments) Descriptor() ([]byte, []int) {
	return file_server_example_proto_rawDescGZIP(), []int{2}
}

var File_server_example_proto protoreflect.FileDescriptor

var file_server_example_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x26, 0x0a, 0x0a,
	0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x22, 0x26, 0x0a, 0x0a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x0d, 0x0a, 0x0b,
	0x4e, 0x6f, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x32, 0xbf, 0x01, 0x0a, 0x0d,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x36, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12, 0x11,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4e, 0x6f, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x73, 0x1a, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x48, 0x69, 0x64, 0x64,
	0x65, 0x6e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x44, 0x61, 0x74, 0x61, 0x12, 0x11, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x4e, 0x6f, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a,
	0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x00, 0x30, 0x01, 0x12, 0x36, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x11, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x4e, 0x6f,
	0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x10, 0x2e, 0x6d, 0x61, 0x69, 0x6e,
	0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x44, 0x61, 0x74, 0x61, 0x22, 0x00, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x3b, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_server_example_proto_rawDescOnce sync.Once
	file_server_example_proto_rawDescData = file_server_example_proto_rawDesc
)

func file_server_example_proto_rawDescGZIP() []byte {
	file_server_example_proto_rawDescOnce.Do(func() {
		file_server_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_example_proto_rawDescData)
	})
	return file_server_example_proto_rawDescData
}

var file_server_example_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_server_example_proto_goTypes = []interface{}{
	(*HiddenData)(nil),  // 0: main.HiddenData
	(*PublicData)(nil),  // 1: main.PublicData
	(*NoArguments)(nil), // 2: main.NoArguments
}
var file_server_example_proto_depIdxs = []int32{
	2, // 0: main.ServerExample.GetHiddenData:input_type -> main.NoArguments
	2, // 1: main.ServerExample.GetHiddenStreamData:input_type -> main.NoArguments
	2, // 2: main.ServerExample.GetPublicData:input_type -> main.NoArguments
	0, // 3: main.ServerExample.GetHiddenData:output_type -> main.HiddenData
	0, // 4: main.ServerExample.GetHiddenStreamData:output_type -> main.HiddenData
	1, // 5: main.ServerExample.GetPublicData:output_type -> main.PublicData
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_server_example_proto_init() }
func file_server_example_proto_init() {
	if File_server_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HiddenData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublicData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_example_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoArguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_example_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_example_proto_goTypes,
		DependencyIndexes: file_server_example_proto_depIdxs,
		MessageInfos:      file_server_example_proto_msgTypes,
	}.Build()
	File_server_example_proto = out.File
	file_server_example_proto_rawDesc = nil
	file_server_example_proto_goTypes = nil
	file_server_example_proto_depIdxs = nil
}
