// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: server_example.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServerExampleClient is the client API for ServerExample service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerExampleClient interface {
	GetHiddenData(ctx context.Context, in *NoArguments, opts ...grpc.CallOption) (*HiddenData, error)
	GetHiddenStreamData(ctx context.Context, in *NoArguments, opts ...grpc.CallOption) (ServerExample_GetHiddenStreamDataClient, error)
	GetPublicData(ctx context.Context, in *NoArguments, opts ...grpc.CallOption) (*PublicData, error)
}

type serverExampleClient struct {
	cc grpc.ClientConnInterface
}

func NewServerExampleClient(cc grpc.ClientConnInterface) ServerExampleClient {
	return &serverExampleClient{cc}
}

func (c *serverExampleClient) GetHiddenData(ctx context.Context, in *NoArguments, opts ...grpc.CallOption) (*HiddenData, error) {
	out := new(HiddenData)
	err := c.cc.Invoke(ctx, "/main.ServerExample/GetHiddenData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverExampleClient) GetHiddenStreamData(ctx context.Context, in *NoArguments, opts ...grpc.CallOption) (ServerExample_GetHiddenStreamDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &ServerExample_ServiceDesc.Streams[0], "/main.ServerExample/GetHiddenStreamData", opts...)
	if err != nil {
		return nil, err
	}
	x := &serverExampleGetHiddenStreamDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ServerExample_GetHiddenStreamDataClient interface {
	Recv() (*HiddenData, error)
	grpc.ClientStream
}

type serverExampleGetHiddenStreamDataClient struct {
	grpc.ClientStream
}

func (x *serverExampleGetHiddenStreamDataClient) Recv() (*HiddenData, error) {
	m := new(HiddenData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *serverExampleClient) GetPublicData(ctx context.Context, in *NoArguments, opts ...grpc.CallOption) (*PublicData, error) {
	out := new(PublicData)
	err := c.cc.Invoke(ctx, "/main.ServerExample/GetPublicData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerExampleServer is the server API for ServerExample service.
// All implementations must embed UnimplementedServerExampleServer
// for forward compatibility
type ServerExampleServer interface {
	GetHiddenData(context.Context, *NoArguments) (*HiddenData, error)
	GetHiddenStreamData(*NoArguments, ServerExample_GetHiddenStreamDataServer) error
	GetPublicData(context.Context, *NoArguments) (*PublicData, error)
	mustEmbedUnimplementedServerExampleServer()
}

// UnimplementedServerExampleServer must be embedded to have forward compatible implementations.
type UnimplementedServerExampleServer struct {
}

func (UnimplementedServerExampleServer) GetHiddenData(context.Context, *NoArguments) (*HiddenData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHiddenData not implemented")
}
func (UnimplementedServerExampleServer) GetHiddenStreamData(*NoArguments, ServerExample_GetHiddenStreamDataServer) error {
	return status.Errorf(codes.Unimplemented, "method GetHiddenStreamData not implemented")
}
func (UnimplementedServerExampleServer) GetPublicData(context.Context, *NoArguments) (*PublicData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicData not implemented")
}
func (UnimplementedServerExampleServer) mustEmbedUnimplementedServerExampleServer() {}

// UnsafeServerExampleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerExampleServer will
// result in compilation errors.
type UnsafeServerExampleServer interface {
	mustEmbedUnimplementedServerExampleServer()
}

func RegisterServerExampleServer(s grpc.ServiceRegistrar, srv ServerExampleServer) {
	s.RegisterService(&ServerExample_ServiceDesc, srv)
}

func _ServerExample_GetHiddenData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoArguments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerExampleServer).GetHiddenData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ServerExample/GetHiddenData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerExampleServer).GetHiddenData(ctx, req.(*NoArguments))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServerExample_GetHiddenStreamData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NoArguments)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServerExampleServer).GetHiddenStreamData(m, &serverExampleGetHiddenStreamDataServer{stream})
}

type ServerExample_GetHiddenStreamDataServer interface {
	Send(*HiddenData) error
	grpc.ServerStream
}

type serverExampleGetHiddenStreamDataServer struct {
	grpc.ServerStream
}

func (x *serverExampleGetHiddenStreamDataServer) Send(m *HiddenData) error {
	return x.ServerStream.SendMsg(m)
}

func _ServerExample_GetPublicData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoArguments)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerExampleServer).GetPublicData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ServerExample/GetPublicData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerExampleServer).GetPublicData(ctx, req.(*NoArguments))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerExample_ServiceDesc is the grpc.ServiceDesc for ServerExample service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerExample_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "main.ServerExample",
	HandlerType: (*ServerExampleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHiddenData",
			Handler:    _ServerExample_GetHiddenData_Handler,
		},
		{
			MethodName: "GetPublicData",
			Handler:    _ServerExample_GetPublicData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetHiddenStreamData",
			Handler:       _ServerExample_GetHiddenStreamData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server_example.proto",
}
